### ISSUE TITLE
Can't run the website locally

### ISSUE THREAD

**Issue by CHR-onicles** [pmessan/simple-blog#1]
Followed the instructions in the README but still can't run the site locally.
 (I installed nodemon with `npm install -g nodemon` btw)

**Screenshot:**
Seems its running, but does not launch in my browser.

![image](https://user-images.githubusercontent.com/44934037/118523131-5e17e380-b72c-11eb-9622-1aab3290c735.png)

**Comment by pmessan** [comment]
Hey,
So this error appears when your MongoDB server isn't running. The Node server is trying to connect and doesn't succeed, therefore the page can't load.

Things to check:

- Is MongoDB installed?
- Is the mongo daemon running? (You can check that with `pgrep mongod` if nothing is returned, then your daemon isn't running.)
- Make sure you are in the main directory of the repo, and run `npm i` to install the dependencies. I'll add that to the readme

**Comment by CHR-onicles** [comment]
Hey, 

I installed `mongodb` and added it to my `environment path`. Took care of the errors for now, but still the site does not launch in my browser.

It shows that `mongod` is running in my terminal.

Also it seems `pgrep` is a [unix command](https://superuser.com/questions/1115407/grep-is-not-recognized-as-an-internal-or-external-in-windows) no?... im on windows 10 btw.

![image](https://user-images.githubusercontent.com/44934037/118565524-da78e980-b761-11eb-9b67-1df175bbcfc1.png)

Thanks in advance.

Edit: added link.

**Comment by pmessan** [comment]
No worries. This server does not automatically launch your browser. Just open your browser and type in `localhost:3000` and you should see the site.

Cheers!

**Comment by CHR-onicles** [comment]
aww man... works now haha...thanks a lot 👍🏼
